# Generated by Django 4.0.5 on 2022-07-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='headline',
            field=models.TextField(),
        ),
    ]
