# Generated by Django 4.0.5 on 2022-07-26 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_newspost_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='newspost',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newspost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
