# Generated by Django 4.0.5 on 2022-08-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_newspost_options_newspost_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
