# Generated by Django 4.0.5 on 2022-08-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_delete_newspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General', 'General'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Technology', 'Technology')], default='General', max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.categore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('images', models.ImageField(upload_to='newsimage')),
                ('reporter', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Published'), ('2', 'Unpublished')], default='2', max_length=50)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cata', to='app.categore')),
                ('sub_categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcata', to='app.subcategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
