# Generated by Django 4.0.5 on 2022-08-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_subcategory_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='sub_categori',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
