# Generated by Django 4.0.5 on 2022-08-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_newspost_sub_categori_delete_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTopNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('short_description', models.TextField()),
                ('details', models.TextField()),
                ('images', models.ImageField(upload_to='newsimage')),
                ('reporter', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Published'), ('2', 'Unpublished')], default='2', max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.categore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
